name: flutter_mvvm
description: "MVVM architecture for Flutter"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # APP STATE
  hooks_riverpod: ^2.6.1
  flutter_hooks:
  riverpod_annotation: ^2.6.1
  freezed_annotation:

  # DEPENDENCIES
  get_it: ^8.0.2
  injectable: ^2.5.0

  # ROUTING
  routefly: ^2.0.4

  # UTILS
  async: ^2.11.0
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  injectable_generator:
  custom_lint:
  riverpod_generator:
  riverpod_lint:
  freezed:
  json_serializable:

flutter:
  uses-material-design: true
